name       : runc
version    : 1.1.7
release    : 24
source     :
    - https://github.com/opencontainers/runc/archive/refs/tags/v1.1.7.tar.gz : f1885d6dfa188f8112328ac2355e5d67346174a2e2e795ec514a972bcbfcc2fa
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - pkgconfig(libseccomp)
    - go-md2man
    - golang
networking : yes
setup      : |
    mkdir -p src/github.com/opencontainers/runc
    find ./* -prune ! -name src -exec mv {} src/github.com/opencontainers/runc/ \;
environment: |
    export GOPATH="`pwd`"
    export BUILDTAGS='seccomp apparmor'
    export CGO_CPPFLAGS="${CPPFLAGS}"
    export CGO_CFLAGS="${CFLAGS}"
    export CGO_CXXFLAGS="${CXXFLAGS}"
    export CGO_LDFLAGS="${LDFLAGS}"
    export GOFLAGS="-trimpath -mod=readonly -modcacherw"

    # Git SHA corresponding to the release tag
    export COMMIT=5fd4c4d144137e991c4acebb2146ab1483a97925
build      : |
    cd src/github.com/opencontainers/runc
    %make runc man
install    : |
    cd src/github.com/opencontainers/runc/
    install -Dm00755 runc $installdir/usr/bin/runc

    install -Dm00644 contrib/completions/bash/runc $installdir/usr/share/bash-completion/completions/runc

    install -d $installdir/usr/share/man/man8
    install -m644 man/man8/*.8 $installdir/usr/share/man/man8
