name       : runc
version    : 1.0.2
release    : 18
source     :
    - https://github.com/opencontainers/runc/archive/refs/tags/v1.0.2.tar.gz : 6c3cca4bbeb5d9b2f5e3c0c401c9d27bc8a5d2a0db8a2f6a06efd03ad3c38a33
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - pkgconfig(libseccomp)
    - golang
setup      : |
    mkdir -p src/github.com/opencontainers/runc
    find ./* -prune ! -name src -exec mv {} src/github.com/opencontainers/runc/ \;
environment: |
    export GOPATH="`pwd`"
build      : |
    %make -C src/github.com/opencontainers/runc
install    : |
    install -Dm00755 src/github.com/opencontainers/runc/runc $installdir/usr/bin/runc
