name       : runc
version    : 1.0.0_rc2
release    : 3
source     :
    - https://github.com/opencontainers/runc/archive/v1.0.0-rc2.tar.gz : 638742c48426b9a3281aeb619e27513d972de228bdbd43b478baea99c186d491
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
strip      : no
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - golang
    - pkgconfig(libseccomp)
build      : |
    mkdir -p src/github.com/opencontainers
    ln -s `pwd` src/github.com/opencontainers/runc
    export GOPATH="`pwd`:%libdir%/golang"
    %make LDFLAGS=
install    : |
    install -D -m 00755 runc $installdir/usr/bin/runc
