name       : runc
version    : 1.0.0_rc4
release    : 7
source     :
    - git|https://github.com/opencontainers/runc.git : v1.0.0-rc4
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
strip      : no
extract    : no
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - pkgconfig(libseccomp)
    - golang
setup      : |
    mkdir -p go/src/github.com/opencontainers
    cp -R $sources/runc.git go/src/github.com/opencontainers/runc
build      : |
    export GOPATH=$workdir/
    cd src/github.com/opencontainers/runc
    %make LDFLAGS=
install    : |
    install -D -m 00755 src/github.com/opencontainers/runc/runc $installdir/usr/bin/runc
