name       : runc
version    : 1.0.0_rc6
release    : 11
source     :
    - https://github.com/opencontainers/runc/archive/v1.0.0-rc6.tar.gz : a221f8380e7b5806031f54d423af6dde24c305dad49868056cf70e5f5f4ef771
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - pkgconfig(libseccomp)
    - golang
setup      : |
    %patch -Np1 < $pkgfiles/security/0001-nsenter-clone-proc-self-exe-to-avoid-exposing-host-b.patch
build      : |
    mkdir -p src/github.com/opencontainers
    ln -s `pwd` src/github.com/opencontainers/runc
    export GOPATH="`pwd`"
    pushd src/github.com/opencontainers/runc
    %make LDFLAGS= COMMIT="ccb5efd37fb7c86364786e9137e22948751de7ed"
install    : |
    install -Dm00755 src/github.com/opencontainers/runc/runc $installdir/usr/bin/runc
