name       : runc
version    : 1.0.3
release    : 19
source     :
    - https://github.com/opencontainers/runc/archive/refs/tags/v1.0.3.tar.gz : 0eaf2f6606d72f166a5e7138a8a8d4d8f85d84e43448c08c66a1c93ead17a574
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - pkgconfig(libseccomp)
    - golang
setup      : |
    mkdir -p src/github.com/opencontainers/runc
    find ./* -prune ! -name src -exec mv {} src/github.com/opencontainers/runc/ \;
environment: |
    export GOPATH="`pwd`"
build      : |
    %make -C src/github.com/opencontainers/runc
install    : |
    install -Dm00755 src/github.com/opencontainers/runc/runc $installdir/usr/bin/runc
