name       : runc
version    : 1.0.0_rc1
release    : 2
source     :
    - https://github.com/opencontainers/runc/archive/v1.0.0-rc1.tar.gz : 77f9d4df1657fecc939be0261fcccccd34d5b22c02b8a49abad23fac33b4059a
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
strip      : no
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - golang
    - pkgconfig(libseccomp)
build      : |
    mkdir -p src/github.com/opencontainers
    ln -s `pwd` src/github.com/opencontainers/runc
    export GOPATH="`pwd`:%libdir%/golang"
    %make LDFLAGS=
install    : |
    install -D -m 00755 runc $installdir/usr/bin/runc
