name       : runc
version    : 1.1.2
release    : 21
source     :
    - https://github.com/opencontainers/runc/archive/refs/tags/v1.1.2.tar.gz : 0ccce82b1d9c058d8fd7443d261c96fd7a803f2775bcb1fec2bdb725bc7640f6
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - pkgconfig(libseccomp)
    - golang
setup      : |
    mkdir -p src/github.com/opencontainers/runc
    find ./* -prune ! -name src -exec mv {} src/github.com/opencontainers/runc/ \;
environment: |
    export GOPATH="`pwd`"
build      : |
    %make -C src/github.com/opencontainers/runc
install    : |
    install -Dm00755 src/github.com/opencontainers/runc/runc $installdir/usr/bin/runc
