name       : runc
version    : 1.0.0_rc10
release    : 14
source     :
    - https://github.com/opencontainers/runc/archive/v1.0.0-rc10.tar.gz : 6b44985023347fb9c5a2cc6f761df8c41cc2c84a7a68a6e6acf834dff6653a9a
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - pkgconfig(libseccomp)
    - golang
build      : |
    mkdir -p src/github.com/opencontainers
    ln -s `pwd` src/github.com/opencontainers/runc
    export GOPATH="`pwd`"
    pushd src/github.com/opencontainers/runc
    %make LDFLAGS= COMMIT="ccb5efd37fb7c86364786e9137e22948751de7ed"
install    : |
    install -Dm00755 src/github.com/opencontainers/runc/runc $installdir/usr/bin/runc
