name       : runc
version    : 1.0.0_rc5
release    : 8
source     :
    - https://github.com/opencontainers/runc/archive/v1.0.0-rc5.tar.gz : 770e180d1cca1f3c1a67512ebf9720caafe97af4fc2fe12fa43a3cf7bfa77522
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - pkgconfig(libseccomp)
    - golang
build      : |
    mkdir -p src/github.com/opencontainers
    ln -s `pwd` src/github.com/opencontainers/runc
    export GOPATH="`pwd`"
    pushd src/github.com/opencontainers/runc
    %make LDFLAGS=
install    : |
    install -D -m 00755 src/github.com/opencontainers/runc/runc $installdir/usr/bin/runc
