name       : runc
version    : 1.0.0_rc9
release    : 13
source     :
    - https://github.com/opencontainers/runc/archive/v1.0.0-rc9.tar.gz : 2ec69c25df9f02c6fd38eb287145f8afba6772f809abe01df4534b5bfd68e8d4
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - pkgconfig(libseccomp)
    - golang
build      : |
    mkdir -p src/github.com/opencontainers
    ln -s `pwd` src/github.com/opencontainers/runc
    export GOPATH="`pwd`"
    pushd src/github.com/opencontainers/runc
    %make LDFLAGS= COMMIT="ccb5efd37fb7c86364786e9137e22948751de7ed"
install    : |
    install -Dm00755 src/github.com/opencontainers/runc/runc $installdir/usr/bin/runc
