name       : runc
version    : 1.0.0_rc3
release    : 6
source     :
    - git|https://github.com/docker/runc.git : 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
license    : Apache-2.0
component  : virt
summary    : OCI complaint CLI tool to run containers
strip      : no
extract    : no
description: |
    runc is a CLI tool for spawning and running containers according to the OCI specification.
builddeps  :
    - pkgconfig(libseccomp)
    - golang
setup      : |
    mkdir -p go/src/github.com/docker
    cp -R $sources/runc.git go/src/github.com/docker/runc
build      : |
    export GOPATH=$workdir/
    cd src/github.com/docker/runc
    %make LDFLAGS=
install    : |
    install -D -m 00755 src/github.com/docker/runc/runc $installdir/usr/bin/runc
